// Code generated by hertz generator.

package workflow

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _executionsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listexecutionsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getexecutionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _cancelexecutionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pauseexecutionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _retryexecutionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _workflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getworkflowstatsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _workflowsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listworkflowsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _id0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getworkflowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _executeworkflowMw() []app.HandlerFunc {
	// your code...
	return nil
}
