// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	chat "github.com/fuhanyang/CYGlowFlow/app/gateway/biz/router/chat"
	friend "github.com/fuhanyang/CYGlowFlow/app/gateway/biz/router/friend"
	home "github.com/fuhanyang/CYGlowFlow/app/gateway/biz/router/home"
	login "github.com/fuhanyang/CYGlowFlow/app/gateway/biz/router/login"
	news "github.com/fuhanyang/CYGlowFlow/app/gateway/biz/router/news"
	user "github.com/fuhanyang/CYGlowFlow/app/gateway/biz/router/user"
	workflow "github.com/fuhanyang/CYGlowFlow/app/gateway/biz/router/workflow"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	user.Register(r)

	workflow.Register(r)

	news.Register(r)

	friend.Register(r)

	home.Register(r)

	login.Register(r)

	chat.Register(r)
}
