// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/fuhanyang/CYGlowFlow/app/user/biz/dal/mysql/model"
)

func newGatewayAccessLog(db *gorm.DB, opts ...gen.DOOption) gatewayAccessLog {
	_gatewayAccessLog := gatewayAccessLog{}

	_gatewayAccessLog.gatewayAccessLogDo.UseDB(db, opts...)
	_gatewayAccessLog.gatewayAccessLogDo.UseModel(&model.GatewayAccessLog{})

	tableName := _gatewayAccessLog.gatewayAccessLogDo.TableName()
	_gatewayAccessLog.ALL = field.NewAsterisk(tableName)
	_gatewayAccessLog.ID = field.NewUint64(tableName, "id")
	_gatewayAccessLog.TraceID = field.NewString(tableName, "trace_id")
	_gatewayAccessLog.UserID = field.NewUint64(tableName, "user_id")
	_gatewayAccessLog.IP = field.NewString(tableName, "ip")
	_gatewayAccessLog.Method = field.NewString(tableName, "method")
	_gatewayAccessLog.Path = field.NewString(tableName, "path")
	_gatewayAccessLog.Query = field.NewString(tableName, "query")
	_gatewayAccessLog.Body = field.NewString(tableName, "body")
	_gatewayAccessLog.StatusCode = field.NewInt32(tableName, "status_code")
	_gatewayAccessLog.Latency = field.NewInt64(tableName, "latency")
	_gatewayAccessLog.ErrorMsg = field.NewString(tableName, "error_msg")
	_gatewayAccessLog.CreatedAt = field.NewTime(tableName, "created_at")

	_gatewayAccessLog.fillFieldMap()

	return _gatewayAccessLog
}

// gatewayAccessLog 网关访问日志表
type gatewayAccessLog struct {
	gatewayAccessLogDo gatewayAccessLogDo

	ALL        field.Asterisk
	ID         field.Uint64
	TraceID    field.String // 链路追踪ID
	UserID     field.Uint64 // 用户ID(未登录为0)
	IP         field.String // 访问IP
	Method     field.String // 请求方法
	Path       field.String // 请求路径
	Query      field.String // 查询参数
	Body       field.String // 请求体(可选截取)
	StatusCode field.Int32  // HTTP状态码
	Latency    field.Int64  // 耗时(毫秒)
	ErrorMsg   field.String // 错误信息
	CreatedAt  field.Time   // 请求时间

	fieldMap map[string]field.Expr
}

func (g gatewayAccessLog) Table(newTableName string) *gatewayAccessLog {
	g.gatewayAccessLogDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g gatewayAccessLog) As(alias string) *gatewayAccessLog {
	g.gatewayAccessLogDo.DO = *(g.gatewayAccessLogDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *gatewayAccessLog) updateTableName(table string) *gatewayAccessLog {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewUint64(table, "id")
	g.TraceID = field.NewString(table, "trace_id")
	g.UserID = field.NewUint64(table, "user_id")
	g.IP = field.NewString(table, "ip")
	g.Method = field.NewString(table, "method")
	g.Path = field.NewString(table, "path")
	g.Query = field.NewString(table, "query")
	g.Body = field.NewString(table, "body")
	g.StatusCode = field.NewInt32(table, "status_code")
	g.Latency = field.NewInt64(table, "latency")
	g.ErrorMsg = field.NewString(table, "error_msg")
	g.CreatedAt = field.NewTime(table, "created_at")

	g.fillFieldMap()

	return g
}

func (g *gatewayAccessLog) WithContext(ctx context.Context) IGatewayAccessLogDo {
	return g.gatewayAccessLogDo.WithContext(ctx)
}

func (g gatewayAccessLog) TableName() string { return g.gatewayAccessLogDo.TableName() }

func (g gatewayAccessLog) Alias() string { return g.gatewayAccessLogDo.Alias() }

func (g gatewayAccessLog) Columns(cols ...field.Expr) gen.Columns {
	return g.gatewayAccessLogDo.Columns(cols...)
}

func (g *gatewayAccessLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *gatewayAccessLog) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 12)
	g.fieldMap["id"] = g.ID
	g.fieldMap["trace_id"] = g.TraceID
	g.fieldMap["user_id"] = g.UserID
	g.fieldMap["ip"] = g.IP
	g.fieldMap["method"] = g.Method
	g.fieldMap["path"] = g.Path
	g.fieldMap["query"] = g.Query
	g.fieldMap["body"] = g.Body
	g.fieldMap["status_code"] = g.StatusCode
	g.fieldMap["latency"] = g.Latency
	g.fieldMap["error_msg"] = g.ErrorMsg
	g.fieldMap["created_at"] = g.CreatedAt
}

func (g gatewayAccessLog) clone(db *gorm.DB) gatewayAccessLog {
	g.gatewayAccessLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g gatewayAccessLog) replaceDB(db *gorm.DB) gatewayAccessLog {
	g.gatewayAccessLogDo.ReplaceDB(db)
	return g
}

type gatewayAccessLogDo struct{ gen.DO }

type IGatewayAccessLogDo interface {
	gen.SubQuery
	Debug() IGatewayAccessLogDo
	WithContext(ctx context.Context) IGatewayAccessLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGatewayAccessLogDo
	WriteDB() IGatewayAccessLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGatewayAccessLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGatewayAccessLogDo
	Not(conds ...gen.Condition) IGatewayAccessLogDo
	Or(conds ...gen.Condition) IGatewayAccessLogDo
	Select(conds ...field.Expr) IGatewayAccessLogDo
	Where(conds ...gen.Condition) IGatewayAccessLogDo
	Order(conds ...field.Expr) IGatewayAccessLogDo
	Distinct(cols ...field.Expr) IGatewayAccessLogDo
	Omit(cols ...field.Expr) IGatewayAccessLogDo
	Join(table schema.Tabler, on ...field.Expr) IGatewayAccessLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGatewayAccessLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGatewayAccessLogDo
	Group(cols ...field.Expr) IGatewayAccessLogDo
	Having(conds ...gen.Condition) IGatewayAccessLogDo
	Limit(limit int) IGatewayAccessLogDo
	Offset(offset int) IGatewayAccessLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGatewayAccessLogDo
	Unscoped() IGatewayAccessLogDo
	Create(values ...*model.GatewayAccessLog) error
	CreateInBatches(values []*model.GatewayAccessLog, batchSize int) error
	Save(values ...*model.GatewayAccessLog) error
	First() (*model.GatewayAccessLog, error)
	Take() (*model.GatewayAccessLog, error)
	Last() (*model.GatewayAccessLog, error)
	Find() ([]*model.GatewayAccessLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GatewayAccessLog, err error)
	FindInBatches(result *[]*model.GatewayAccessLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.GatewayAccessLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGatewayAccessLogDo
	Assign(attrs ...field.AssignExpr) IGatewayAccessLogDo
	Joins(fields ...field.RelationField) IGatewayAccessLogDo
	Preload(fields ...field.RelationField) IGatewayAccessLogDo
	FirstOrInit() (*model.GatewayAccessLog, error)
	FirstOrCreate() (*model.GatewayAccessLog, error)
	FindByPage(offset int, limit int) (result []*model.GatewayAccessLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGatewayAccessLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g gatewayAccessLogDo) Debug() IGatewayAccessLogDo {
	return g.withDO(g.DO.Debug())
}

func (g gatewayAccessLogDo) WithContext(ctx context.Context) IGatewayAccessLogDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g gatewayAccessLogDo) ReadDB() IGatewayAccessLogDo {
	return g.Clauses(dbresolver.Read)
}

func (g gatewayAccessLogDo) WriteDB() IGatewayAccessLogDo {
	return g.Clauses(dbresolver.Write)
}

func (g gatewayAccessLogDo) Session(config *gorm.Session) IGatewayAccessLogDo {
	return g.withDO(g.DO.Session(config))
}

func (g gatewayAccessLogDo) Clauses(conds ...clause.Expression) IGatewayAccessLogDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g gatewayAccessLogDo) Returning(value interface{}, columns ...string) IGatewayAccessLogDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g gatewayAccessLogDo) Not(conds ...gen.Condition) IGatewayAccessLogDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g gatewayAccessLogDo) Or(conds ...gen.Condition) IGatewayAccessLogDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g gatewayAccessLogDo) Select(conds ...field.Expr) IGatewayAccessLogDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g gatewayAccessLogDo) Where(conds ...gen.Condition) IGatewayAccessLogDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g gatewayAccessLogDo) Order(conds ...field.Expr) IGatewayAccessLogDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g gatewayAccessLogDo) Distinct(cols ...field.Expr) IGatewayAccessLogDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g gatewayAccessLogDo) Omit(cols ...field.Expr) IGatewayAccessLogDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g gatewayAccessLogDo) Join(table schema.Tabler, on ...field.Expr) IGatewayAccessLogDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g gatewayAccessLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGatewayAccessLogDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g gatewayAccessLogDo) RightJoin(table schema.Tabler, on ...field.Expr) IGatewayAccessLogDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g gatewayAccessLogDo) Group(cols ...field.Expr) IGatewayAccessLogDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g gatewayAccessLogDo) Having(conds ...gen.Condition) IGatewayAccessLogDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g gatewayAccessLogDo) Limit(limit int) IGatewayAccessLogDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g gatewayAccessLogDo) Offset(offset int) IGatewayAccessLogDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g gatewayAccessLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGatewayAccessLogDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g gatewayAccessLogDo) Unscoped() IGatewayAccessLogDo {
	return g.withDO(g.DO.Unscoped())
}

func (g gatewayAccessLogDo) Create(values ...*model.GatewayAccessLog) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g gatewayAccessLogDo) CreateInBatches(values []*model.GatewayAccessLog, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g gatewayAccessLogDo) Save(values ...*model.GatewayAccessLog) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g gatewayAccessLogDo) First() (*model.GatewayAccessLog, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GatewayAccessLog), nil
	}
}

func (g gatewayAccessLogDo) Take() (*model.GatewayAccessLog, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GatewayAccessLog), nil
	}
}

func (g gatewayAccessLogDo) Last() (*model.GatewayAccessLog, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GatewayAccessLog), nil
	}
}

func (g gatewayAccessLogDo) Find() ([]*model.GatewayAccessLog, error) {
	result, err := g.DO.Find()
	return result.([]*model.GatewayAccessLog), err
}

func (g gatewayAccessLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GatewayAccessLog, err error) {
	buf := make([]*model.GatewayAccessLog, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g gatewayAccessLogDo) FindInBatches(result *[]*model.GatewayAccessLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g gatewayAccessLogDo) Attrs(attrs ...field.AssignExpr) IGatewayAccessLogDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g gatewayAccessLogDo) Assign(attrs ...field.AssignExpr) IGatewayAccessLogDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g gatewayAccessLogDo) Joins(fields ...field.RelationField) IGatewayAccessLogDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g gatewayAccessLogDo) Preload(fields ...field.RelationField) IGatewayAccessLogDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g gatewayAccessLogDo) FirstOrInit() (*model.GatewayAccessLog, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GatewayAccessLog), nil
	}
}

func (g gatewayAccessLogDo) FirstOrCreate() (*model.GatewayAccessLog, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GatewayAccessLog), nil
	}
}

func (g gatewayAccessLogDo) FindByPage(offset int, limit int) (result []*model.GatewayAccessLog, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g gatewayAccessLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g gatewayAccessLogDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g gatewayAccessLogDo) Delete(models ...*model.GatewayAccessLog) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *gatewayAccessLogDo) withDO(do gen.Dao) *gatewayAccessLogDo {
	g.DO = *do.(*gen.DO)
	return g
}
