// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/fuhanyang/CYGlowFlow/app/user/biz/dal/mysql/model"
)

func newGatewayBlacklist(db *gorm.DB, opts ...gen.DOOption) gatewayBlacklist {
	_gatewayBlacklist := gatewayBlacklist{}

	_gatewayBlacklist.gatewayBlacklistDo.UseDB(db, opts...)
	_gatewayBlacklist.gatewayBlacklistDo.UseModel(&model.GatewayBlacklist{})

	tableName := _gatewayBlacklist.gatewayBlacklistDo.TableName()
	_gatewayBlacklist.ALL = field.NewAsterisk(tableName)
	_gatewayBlacklist.ID = field.NewUint64(tableName, "id")
	_gatewayBlacklist.Type = field.NewInt32(tableName, "type")
	_gatewayBlacklist.Value = field.NewString(tableName, "value")
	_gatewayBlacklist.Reason = field.NewString(tableName, "reason")
	_gatewayBlacklist.ExpireAt = field.NewTime(tableName, "expire_at")
	_gatewayBlacklist.Enable = field.NewInt32(tableName, "enable")
	_gatewayBlacklist.CreatedAt = field.NewTime(tableName, "created_at")
	_gatewayBlacklist.UpdatedAt = field.NewTime(tableName, "updated_at")

	_gatewayBlacklist.fillFieldMap()

	return _gatewayBlacklist
}

// gatewayBlacklist 网关黑名单表
type gatewayBlacklist struct {
	gatewayBlacklistDo gatewayBlacklistDo

	ALL       field.Asterisk
	ID        field.Uint64
	Type      field.Int32  // 类型 1:IP 2:UserID
	Value     field.String // 黑名单值(IP或ID)
	Reason    field.String // 封禁原因
	ExpireAt  field.Time   // 过期时间(NULL为永久)
	Enable    field.Int32  // 是否生效
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (g gatewayBlacklist) Table(newTableName string) *gatewayBlacklist {
	g.gatewayBlacklistDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g gatewayBlacklist) As(alias string) *gatewayBlacklist {
	g.gatewayBlacklistDo.DO = *(g.gatewayBlacklistDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *gatewayBlacklist) updateTableName(table string) *gatewayBlacklist {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewUint64(table, "id")
	g.Type = field.NewInt32(table, "type")
	g.Value = field.NewString(table, "value")
	g.Reason = field.NewString(table, "reason")
	g.ExpireAt = field.NewTime(table, "expire_at")
	g.Enable = field.NewInt32(table, "enable")
	g.CreatedAt = field.NewTime(table, "created_at")
	g.UpdatedAt = field.NewTime(table, "updated_at")

	g.fillFieldMap()

	return g
}

func (g *gatewayBlacklist) WithContext(ctx context.Context) IGatewayBlacklistDo {
	return g.gatewayBlacklistDo.WithContext(ctx)
}

func (g gatewayBlacklist) TableName() string { return g.gatewayBlacklistDo.TableName() }

func (g gatewayBlacklist) Alias() string { return g.gatewayBlacklistDo.Alias() }

func (g gatewayBlacklist) Columns(cols ...field.Expr) gen.Columns {
	return g.gatewayBlacklistDo.Columns(cols...)
}

func (g *gatewayBlacklist) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *gatewayBlacklist) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 8)
	g.fieldMap["id"] = g.ID
	g.fieldMap["type"] = g.Type
	g.fieldMap["value"] = g.Value
	g.fieldMap["reason"] = g.Reason
	g.fieldMap["expire_at"] = g.ExpireAt
	g.fieldMap["enable"] = g.Enable
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
}

func (g gatewayBlacklist) clone(db *gorm.DB) gatewayBlacklist {
	g.gatewayBlacklistDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g gatewayBlacklist) replaceDB(db *gorm.DB) gatewayBlacklist {
	g.gatewayBlacklistDo.ReplaceDB(db)
	return g
}

type gatewayBlacklistDo struct{ gen.DO }

type IGatewayBlacklistDo interface {
	gen.SubQuery
	Debug() IGatewayBlacklistDo
	WithContext(ctx context.Context) IGatewayBlacklistDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGatewayBlacklistDo
	WriteDB() IGatewayBlacklistDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGatewayBlacklistDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGatewayBlacklistDo
	Not(conds ...gen.Condition) IGatewayBlacklistDo
	Or(conds ...gen.Condition) IGatewayBlacklistDo
	Select(conds ...field.Expr) IGatewayBlacklistDo
	Where(conds ...gen.Condition) IGatewayBlacklistDo
	Order(conds ...field.Expr) IGatewayBlacklistDo
	Distinct(cols ...field.Expr) IGatewayBlacklistDo
	Omit(cols ...field.Expr) IGatewayBlacklistDo
	Join(table schema.Tabler, on ...field.Expr) IGatewayBlacklistDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGatewayBlacklistDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGatewayBlacklistDo
	Group(cols ...field.Expr) IGatewayBlacklistDo
	Having(conds ...gen.Condition) IGatewayBlacklistDo
	Limit(limit int) IGatewayBlacklistDo
	Offset(offset int) IGatewayBlacklistDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGatewayBlacklistDo
	Unscoped() IGatewayBlacklistDo
	Create(values ...*model.GatewayBlacklist) error
	CreateInBatches(values []*model.GatewayBlacklist, batchSize int) error
	Save(values ...*model.GatewayBlacklist) error
	First() (*model.GatewayBlacklist, error)
	Take() (*model.GatewayBlacklist, error)
	Last() (*model.GatewayBlacklist, error)
	Find() ([]*model.GatewayBlacklist, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GatewayBlacklist, err error)
	FindInBatches(result *[]*model.GatewayBlacklist, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.GatewayBlacklist) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGatewayBlacklistDo
	Assign(attrs ...field.AssignExpr) IGatewayBlacklistDo
	Joins(fields ...field.RelationField) IGatewayBlacklistDo
	Preload(fields ...field.RelationField) IGatewayBlacklistDo
	FirstOrInit() (*model.GatewayBlacklist, error)
	FirstOrCreate() (*model.GatewayBlacklist, error)
	FindByPage(offset int, limit int) (result []*model.GatewayBlacklist, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGatewayBlacklistDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g gatewayBlacklistDo) Debug() IGatewayBlacklistDo {
	return g.withDO(g.DO.Debug())
}

func (g gatewayBlacklistDo) WithContext(ctx context.Context) IGatewayBlacklistDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g gatewayBlacklistDo) ReadDB() IGatewayBlacklistDo {
	return g.Clauses(dbresolver.Read)
}

func (g gatewayBlacklistDo) WriteDB() IGatewayBlacklistDo {
	return g.Clauses(dbresolver.Write)
}

func (g gatewayBlacklistDo) Session(config *gorm.Session) IGatewayBlacklistDo {
	return g.withDO(g.DO.Session(config))
}

func (g gatewayBlacklistDo) Clauses(conds ...clause.Expression) IGatewayBlacklistDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g gatewayBlacklistDo) Returning(value interface{}, columns ...string) IGatewayBlacklistDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g gatewayBlacklistDo) Not(conds ...gen.Condition) IGatewayBlacklistDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g gatewayBlacklistDo) Or(conds ...gen.Condition) IGatewayBlacklistDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g gatewayBlacklistDo) Select(conds ...field.Expr) IGatewayBlacklistDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g gatewayBlacklistDo) Where(conds ...gen.Condition) IGatewayBlacklistDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g gatewayBlacklistDo) Order(conds ...field.Expr) IGatewayBlacklistDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g gatewayBlacklistDo) Distinct(cols ...field.Expr) IGatewayBlacklistDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g gatewayBlacklistDo) Omit(cols ...field.Expr) IGatewayBlacklistDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g gatewayBlacklistDo) Join(table schema.Tabler, on ...field.Expr) IGatewayBlacklistDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g gatewayBlacklistDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGatewayBlacklistDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g gatewayBlacklistDo) RightJoin(table schema.Tabler, on ...field.Expr) IGatewayBlacklistDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g gatewayBlacklistDo) Group(cols ...field.Expr) IGatewayBlacklistDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g gatewayBlacklistDo) Having(conds ...gen.Condition) IGatewayBlacklistDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g gatewayBlacklistDo) Limit(limit int) IGatewayBlacklistDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g gatewayBlacklistDo) Offset(offset int) IGatewayBlacklistDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g gatewayBlacklistDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGatewayBlacklistDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g gatewayBlacklistDo) Unscoped() IGatewayBlacklistDo {
	return g.withDO(g.DO.Unscoped())
}

func (g gatewayBlacklistDo) Create(values ...*model.GatewayBlacklist) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g gatewayBlacklistDo) CreateInBatches(values []*model.GatewayBlacklist, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g gatewayBlacklistDo) Save(values ...*model.GatewayBlacklist) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g gatewayBlacklistDo) First() (*model.GatewayBlacklist, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GatewayBlacklist), nil
	}
}

func (g gatewayBlacklistDo) Take() (*model.GatewayBlacklist, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GatewayBlacklist), nil
	}
}

func (g gatewayBlacklistDo) Last() (*model.GatewayBlacklist, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GatewayBlacklist), nil
	}
}

func (g gatewayBlacklistDo) Find() ([]*model.GatewayBlacklist, error) {
	result, err := g.DO.Find()
	return result.([]*model.GatewayBlacklist), err
}

func (g gatewayBlacklistDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GatewayBlacklist, err error) {
	buf := make([]*model.GatewayBlacklist, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g gatewayBlacklistDo) FindInBatches(result *[]*model.GatewayBlacklist, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g gatewayBlacklistDo) Attrs(attrs ...field.AssignExpr) IGatewayBlacklistDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g gatewayBlacklistDo) Assign(attrs ...field.AssignExpr) IGatewayBlacklistDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g gatewayBlacklistDo) Joins(fields ...field.RelationField) IGatewayBlacklistDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g gatewayBlacklistDo) Preload(fields ...field.RelationField) IGatewayBlacklistDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g gatewayBlacklistDo) FirstOrInit() (*model.GatewayBlacklist, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GatewayBlacklist), nil
	}
}

func (g gatewayBlacklistDo) FirstOrCreate() (*model.GatewayBlacklist, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GatewayBlacklist), nil
	}
}

func (g gatewayBlacklistDo) FindByPage(offset int, limit int) (result []*model.GatewayBlacklist, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g gatewayBlacklistDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g gatewayBlacklistDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g gatewayBlacklistDo) Delete(models ...*model.GatewayBlacklist) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *gatewayBlacklistDo) withDO(do gen.Dao) *gatewayBlacklistDo {
	g.DO = *do.(*gen.DO)
	return g
}
