// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGatewayBlacklist = "gateway_blacklist"

// GatewayBlacklist 网关黑名单表
type GatewayBlacklist struct {
	ID        uint64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	Type      *int32     `gorm:"column:type;type:tinyint;not null;uniqueIndex:idx_type_val,priority:1;default:1;comment:类型 1:IP 2:UserID" json:"type"` // 类型 1:IP 2:UserID
	Value     string     `gorm:"column:value;type:varchar(64);not null;uniqueIndex:idx_type_val,priority:2;comment:黑名单值(IP或ID)" json:"value"`          // 黑名单值(IP或ID)
	Reason    *string    `gorm:"column:reason;type:varchar(255);comment:封禁原因" json:"reason"`                                                           // 封禁原因
	ExpireAt  *time.Time `gorm:"column:expire_at;type:datetime;index:idx_expire_at,priority:1;comment:过期时间(NULL为永久)" json:"expire_at"`                 // 过期时间(NULL为永久)
	Enable    *int32     `gorm:"column:enable;type:tinyint;not null;default:1;comment:是否生效" json:"enable"`                                             // 是否生效
	CreatedAt *time.Time `gorm:"column:created_at;type:datetime;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:datetime;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName GatewayBlacklist's table name
func (*GatewayBlacklist) TableName() string {
	return TableNameGatewayBlacklist
}
