// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysUserRole = "sys_user_roles"

// SysUserRole 用户角色关联表
type SysUserRole struct {
	UserID uint64 `gorm:"column:user_id;type:bigint unsigned;primaryKey" json:"user_id"`
	RoleID uint64 `gorm:"column:role_id;type:bigint unsigned;primaryKey" json:"role_id"`
}

// TableName SysUserRole's table name
func (*SysUserRole) TableName() string {
	return TableNameSysUserRole
}
