// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysRolePermission = "sys_role_permissions"

// SysRolePermission 角色权限关联表
type SysRolePermission struct {
	RoleID       uint64 `gorm:"column:role_id;type:bigint unsigned;primaryKey" json:"role_id"`
	PermissionID uint64 `gorm:"column:permission_id;type:bigint unsigned;primaryKey" json:"permission_id"`
}

// TableName SysRolePermission's table name
func (*SysRolePermission) TableName() string {
	return TableNameSysRolePermission
}
