// Code generated by Kitex v0.9.1. DO NOT EDIT.

package executionmanagerservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	common "github.com/fuhanyang/CYGlowFlow/rpc_gen/kitex_gen/common"
	exeution_manager "github.com/fuhanyang/CYGlowFlow/rpc_gen/kitex_gen/workflow/infra/exeution_manager"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ExecuteWorkflow(ctx context.Context, Req *exeution_manager.ExecuteWorkflowRequest, callOptions ...callopt.Option) (r *common.BaseResponse, err error)
	ListExecutions(ctx context.Context, Req *exeution_manager.ExecutionQueryRequest, callOptions ...callopt.Option) (r *common.BaseResponse, err error)
	GetExecutionDetail(ctx context.Context, Req *exeution_manager.GetExecutionDetailRequest, callOptions ...callopt.Option) (r *common.BaseResponse, err error)
	CancelExecution(ctx context.Context, Req *exeution_manager.CancelExecutionRequest, callOptions ...callopt.Option) (r *common.BaseResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kExecutionManagerServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kExecutionManagerServiceClient struct {
	*kClient
}

func (p *kExecutionManagerServiceClient) ExecuteWorkflow(ctx context.Context, Req *exeution_manager.ExecuteWorkflowRequest, callOptions ...callopt.Option) (r *common.BaseResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ExecuteWorkflow(ctx, Req)
}

func (p *kExecutionManagerServiceClient) ListExecutions(ctx context.Context, Req *exeution_manager.ExecutionQueryRequest, callOptions ...callopt.Option) (r *common.BaseResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListExecutions(ctx, Req)
}

func (p *kExecutionManagerServiceClient) GetExecutionDetail(ctx context.Context, Req *exeution_manager.GetExecutionDetailRequest, callOptions ...callopt.Option) (r *common.BaseResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetExecutionDetail(ctx, Req)
}

func (p *kExecutionManagerServiceClient) CancelExecution(ctx context.Context, Req *exeution_manager.CancelExecutionRequest, callOptions ...callopt.Option) (r *common.BaseResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CancelExecution(ctx, Req)
}
