// Code generated by Kitex v0.9.1. DO NOT EDIT.

package executionmanagerservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	common "github.com/fuhanyang/CYGlowFlow/rpc_gen/kitex_gen/common"
	exeution_manager "github.com/fuhanyang/CYGlowFlow/rpc_gen/kitex_gen/workflow/infra/exeution_manager"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ExecuteWorkflow": kitex.NewMethodInfo(
		executeWorkflowHandler,
		newExecuteWorkflowArgs,
		newExecuteWorkflowResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListExecutions": kitex.NewMethodInfo(
		listExecutionsHandler,
		newListExecutionsArgs,
		newListExecutionsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetExecutionDetail": kitex.NewMethodInfo(
		getExecutionDetailHandler,
		newGetExecutionDetailArgs,
		newGetExecutionDetailResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CancelExecution": kitex.NewMethodInfo(
		cancelExecutionHandler,
		newCancelExecutionArgs,
		newCancelExecutionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	executionManagerServiceServiceInfo                = NewServiceInfo()
	executionManagerServiceServiceInfoForClient       = NewServiceInfoForClient()
	executionManagerServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return executionManagerServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return executionManagerServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return executionManagerServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ExecutionManagerService"
	handlerType := (*exeution_manager.ExecutionManagerService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "workflow.infra.v1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func executeWorkflowHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(exeution_manager.ExecuteWorkflowRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(exeution_manager.ExecutionManagerService).ExecuteWorkflow(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ExecuteWorkflowArgs:
		success, err := handler.(exeution_manager.ExecutionManagerService).ExecuteWorkflow(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ExecuteWorkflowResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newExecuteWorkflowArgs() interface{} {
	return &ExecuteWorkflowArgs{}
}

func newExecuteWorkflowResult() interface{} {
	return &ExecuteWorkflowResult{}
}

type ExecuteWorkflowArgs struct {
	Req *exeution_manager.ExecuteWorkflowRequest
}

func (p *ExecuteWorkflowArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(exeution_manager.ExecuteWorkflowRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ExecuteWorkflowArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ExecuteWorkflowArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ExecuteWorkflowArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ExecuteWorkflowArgs) Unmarshal(in []byte) error {
	msg := new(exeution_manager.ExecuteWorkflowRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ExecuteWorkflowArgs_Req_DEFAULT *exeution_manager.ExecuteWorkflowRequest

func (p *ExecuteWorkflowArgs) GetReq() *exeution_manager.ExecuteWorkflowRequest {
	if !p.IsSetReq() {
		return ExecuteWorkflowArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ExecuteWorkflowArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ExecuteWorkflowArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ExecuteWorkflowResult struct {
	Success *common.BaseResponse
}

var ExecuteWorkflowResult_Success_DEFAULT *common.BaseResponse

func (p *ExecuteWorkflowResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(common.BaseResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ExecuteWorkflowResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ExecuteWorkflowResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ExecuteWorkflowResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ExecuteWorkflowResult) Unmarshal(in []byte) error {
	msg := new(common.BaseResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ExecuteWorkflowResult) GetSuccess() *common.BaseResponse {
	if !p.IsSetSuccess() {
		return ExecuteWorkflowResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ExecuteWorkflowResult) SetSuccess(x interface{}) {
	p.Success = x.(*common.BaseResponse)
}

func (p *ExecuteWorkflowResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ExecuteWorkflowResult) GetResult() interface{} {
	return p.Success
}

func listExecutionsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(exeution_manager.ExecutionQueryRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(exeution_manager.ExecutionManagerService).ListExecutions(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListExecutionsArgs:
		success, err := handler.(exeution_manager.ExecutionManagerService).ListExecutions(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListExecutionsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListExecutionsArgs() interface{} {
	return &ListExecutionsArgs{}
}

func newListExecutionsResult() interface{} {
	return &ListExecutionsResult{}
}

type ListExecutionsArgs struct {
	Req *exeution_manager.ExecutionQueryRequest
}

func (p *ListExecutionsArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(exeution_manager.ExecutionQueryRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ListExecutionsArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ListExecutionsArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ListExecutionsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListExecutionsArgs) Unmarshal(in []byte) error {
	msg := new(exeution_manager.ExecutionQueryRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListExecutionsArgs_Req_DEFAULT *exeution_manager.ExecutionQueryRequest

func (p *ListExecutionsArgs) GetReq() *exeution_manager.ExecutionQueryRequest {
	if !p.IsSetReq() {
		return ListExecutionsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListExecutionsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListExecutionsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListExecutionsResult struct {
	Success *common.BaseResponse
}

var ListExecutionsResult_Success_DEFAULT *common.BaseResponse

func (p *ListExecutionsResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(common.BaseResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ListExecutionsResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ListExecutionsResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ListExecutionsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListExecutionsResult) Unmarshal(in []byte) error {
	msg := new(common.BaseResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListExecutionsResult) GetSuccess() *common.BaseResponse {
	if !p.IsSetSuccess() {
		return ListExecutionsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListExecutionsResult) SetSuccess(x interface{}) {
	p.Success = x.(*common.BaseResponse)
}

func (p *ListExecutionsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListExecutionsResult) GetResult() interface{} {
	return p.Success
}

func getExecutionDetailHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(exeution_manager.GetExecutionDetailRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(exeution_manager.ExecutionManagerService).GetExecutionDetail(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetExecutionDetailArgs:
		success, err := handler.(exeution_manager.ExecutionManagerService).GetExecutionDetail(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetExecutionDetailResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetExecutionDetailArgs() interface{} {
	return &GetExecutionDetailArgs{}
}

func newGetExecutionDetailResult() interface{} {
	return &GetExecutionDetailResult{}
}

type GetExecutionDetailArgs struct {
	Req *exeution_manager.GetExecutionDetailRequest
}

func (p *GetExecutionDetailArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(exeution_manager.GetExecutionDetailRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetExecutionDetailArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetExecutionDetailArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetExecutionDetailArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetExecutionDetailArgs) Unmarshal(in []byte) error {
	msg := new(exeution_manager.GetExecutionDetailRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetExecutionDetailArgs_Req_DEFAULT *exeution_manager.GetExecutionDetailRequest

func (p *GetExecutionDetailArgs) GetReq() *exeution_manager.GetExecutionDetailRequest {
	if !p.IsSetReq() {
		return GetExecutionDetailArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetExecutionDetailArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetExecutionDetailArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetExecutionDetailResult struct {
	Success *common.BaseResponse
}

var GetExecutionDetailResult_Success_DEFAULT *common.BaseResponse

func (p *GetExecutionDetailResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(common.BaseResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetExecutionDetailResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetExecutionDetailResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetExecutionDetailResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetExecutionDetailResult) Unmarshal(in []byte) error {
	msg := new(common.BaseResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetExecutionDetailResult) GetSuccess() *common.BaseResponse {
	if !p.IsSetSuccess() {
		return GetExecutionDetailResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetExecutionDetailResult) SetSuccess(x interface{}) {
	p.Success = x.(*common.BaseResponse)
}

func (p *GetExecutionDetailResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetExecutionDetailResult) GetResult() interface{} {
	return p.Success
}

func cancelExecutionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(exeution_manager.CancelExecutionRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(exeution_manager.ExecutionManagerService).CancelExecution(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CancelExecutionArgs:
		success, err := handler.(exeution_manager.ExecutionManagerService).CancelExecution(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CancelExecutionResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCancelExecutionArgs() interface{} {
	return &CancelExecutionArgs{}
}

func newCancelExecutionResult() interface{} {
	return &CancelExecutionResult{}
}

type CancelExecutionArgs struct {
	Req *exeution_manager.CancelExecutionRequest
}

func (p *CancelExecutionArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(exeution_manager.CancelExecutionRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *CancelExecutionArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *CancelExecutionArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *CancelExecutionArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CancelExecutionArgs) Unmarshal(in []byte) error {
	msg := new(exeution_manager.CancelExecutionRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CancelExecutionArgs_Req_DEFAULT *exeution_manager.CancelExecutionRequest

func (p *CancelExecutionArgs) GetReq() *exeution_manager.CancelExecutionRequest {
	if !p.IsSetReq() {
		return CancelExecutionArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CancelExecutionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CancelExecutionArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CancelExecutionResult struct {
	Success *common.BaseResponse
}

var CancelExecutionResult_Success_DEFAULT *common.BaseResponse

func (p *CancelExecutionResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(common.BaseResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *CancelExecutionResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *CancelExecutionResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *CancelExecutionResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CancelExecutionResult) Unmarshal(in []byte) error {
	msg := new(common.BaseResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CancelExecutionResult) GetSuccess() *common.BaseResponse {
	if !p.IsSetSuccess() {
		return CancelExecutionResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CancelExecutionResult) SetSuccess(x interface{}) {
	p.Success = x.(*common.BaseResponse)
}

func (p *CancelExecutionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CancelExecutionResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ExecuteWorkflow(ctx context.Context, Req *exeution_manager.ExecuteWorkflowRequest) (r *common.BaseResponse, err error) {
	var _args ExecuteWorkflowArgs
	_args.Req = Req
	var _result ExecuteWorkflowResult
	if err = p.c.Call(ctx, "ExecuteWorkflow", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListExecutions(ctx context.Context, Req *exeution_manager.ExecutionQueryRequest) (r *common.BaseResponse, err error) {
	var _args ListExecutionsArgs
	_args.Req = Req
	var _result ListExecutionsResult
	if err = p.c.Call(ctx, "ListExecutions", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetExecutionDetail(ctx context.Context, Req *exeution_manager.GetExecutionDetailRequest) (r *common.BaseResponse, err error) {
	var _args GetExecutionDetailArgs
	_args.Req = Req
	var _result GetExecutionDetailResult
	if err = p.c.Call(ctx, "GetExecutionDetail", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CancelExecution(ctx context.Context, Req *exeution_manager.CancelExecutionRequest) (r *common.BaseResponse, err error) {
	var _args CancelExecutionArgs
	_args.Req = Req
	var _result CancelExecutionResult
	if err = p.c.Call(ctx, "CancelExecution", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
