// Code generated by Kitex v0.9.1. DO NOT EDIT.

package executionmanagerservice

import (
	server "github.com/cloudwego/kitex/server"
	exeution_manager "github.com/fuhanyang/CYGlowFlow/rpc_gen/kitex_gen/workflow/infra/exeution_manager"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler exeution_manager.ExecutionManagerService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
