// Code generated by Kitex v0.9.1. DO NOT EDIT.
package executionmanagerservice

import (
	server "github.com/cloudwego/kitex/server"
	exeution_manager "github.com/fuhanyang/CYGlowFlow/rpc_gen/kitex_gen/workflow/infra/exeution_manager"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler exeution_manager.ExecutionManagerService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler exeution_manager.ExecutionManagerService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
