// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/fuhanyang/CYGlowFlow/app/gateway/biz/dal/mysql/model"
)

func newGatewayRateLimit(db *gorm.DB, opts ...gen.DOOption) gatewayRateLimit {
	_gatewayRateLimit := gatewayRateLimit{}

	_gatewayRateLimit.gatewayRateLimitDo.UseDB(db, opts...)
	_gatewayRateLimit.gatewayRateLimitDo.UseModel(&model.GatewayRateLimit{})

	tableName := _gatewayRateLimit.gatewayRateLimitDo.TableName()
	_gatewayRateLimit.ALL = field.NewAsterisk(tableName)
	_gatewayRateLimit.ID = field.NewUint64(tableName, "id")
	_gatewayRateLimit.RoutePath = field.NewString(tableName, "route_path")
	_gatewayRateLimit.LimitMethod = field.NewString(tableName, "limit_method")
	_gatewayRateLimit.Capacity = field.NewInt32(tableName, "capacity")
	_gatewayRateLimit.IntervalSec = field.NewInt32(tableName, "interval_sec")
	_gatewayRateLimit.Enable = field.NewInt32(tableName, "enable")
	_gatewayRateLimit.CreatedAt = field.NewTime(tableName, "created_at")
	_gatewayRateLimit.UpdatedAt = field.NewTime(tableName, "updated_at")

	_gatewayRateLimit.fillFieldMap()

	return _gatewayRateLimit
}

// gatewayRateLimit 限流规则表
type gatewayRateLimit struct {
	gatewayRateLimitDo gatewayRateLimitDo

	ALL         field.Asterisk
	ID          field.Uint64
	RoutePath   field.String // 限流的路由路径/规则
	LimitMethod field.String // 限流方法(ALL, GET, POST)
	Capacity    field.Int32  // 令牌桶容量/最大并发数
	IntervalSec field.Int32  // 时间窗口(秒)
	Enable      field.Int32  // 是否开启
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (g gatewayRateLimit) Table(newTableName string) *gatewayRateLimit {
	g.gatewayRateLimitDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g gatewayRateLimit) As(alias string) *gatewayRateLimit {
	g.gatewayRateLimitDo.DO = *(g.gatewayRateLimitDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *gatewayRateLimit) updateTableName(table string) *gatewayRateLimit {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewUint64(table, "id")
	g.RoutePath = field.NewString(table, "route_path")
	g.LimitMethod = field.NewString(table, "limit_method")
	g.Capacity = field.NewInt32(table, "capacity")
	g.IntervalSec = field.NewInt32(table, "interval_sec")
	g.Enable = field.NewInt32(table, "enable")
	g.CreatedAt = field.NewTime(table, "created_at")
	g.UpdatedAt = field.NewTime(table, "updated_at")

	g.fillFieldMap()

	return g
}

func (g *gatewayRateLimit) WithContext(ctx context.Context) IGatewayRateLimitDo {
	return g.gatewayRateLimitDo.WithContext(ctx)
}

func (g gatewayRateLimit) TableName() string { return g.gatewayRateLimitDo.TableName() }

func (g gatewayRateLimit) Alias() string { return g.gatewayRateLimitDo.Alias() }

func (g gatewayRateLimit) Columns(cols ...field.Expr) gen.Columns {
	return g.gatewayRateLimitDo.Columns(cols...)
}

func (g *gatewayRateLimit) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *gatewayRateLimit) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 8)
	g.fieldMap["id"] = g.ID
	g.fieldMap["route_path"] = g.RoutePath
	g.fieldMap["limit_method"] = g.LimitMethod
	g.fieldMap["capacity"] = g.Capacity
	g.fieldMap["interval_sec"] = g.IntervalSec
	g.fieldMap["enable"] = g.Enable
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
}

func (g gatewayRateLimit) clone(db *gorm.DB) gatewayRateLimit {
	g.gatewayRateLimitDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g gatewayRateLimit) replaceDB(db *gorm.DB) gatewayRateLimit {
	g.gatewayRateLimitDo.ReplaceDB(db)
	return g
}

type gatewayRateLimitDo struct{ gen.DO }

type IGatewayRateLimitDo interface {
	gen.SubQuery
	Debug() IGatewayRateLimitDo
	WithContext(ctx context.Context) IGatewayRateLimitDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGatewayRateLimitDo
	WriteDB() IGatewayRateLimitDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGatewayRateLimitDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGatewayRateLimitDo
	Not(conds ...gen.Condition) IGatewayRateLimitDo
	Or(conds ...gen.Condition) IGatewayRateLimitDo
	Select(conds ...field.Expr) IGatewayRateLimitDo
	Where(conds ...gen.Condition) IGatewayRateLimitDo
	Order(conds ...field.Expr) IGatewayRateLimitDo
	Distinct(cols ...field.Expr) IGatewayRateLimitDo
	Omit(cols ...field.Expr) IGatewayRateLimitDo
	Join(table schema.Tabler, on ...field.Expr) IGatewayRateLimitDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGatewayRateLimitDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGatewayRateLimitDo
	Group(cols ...field.Expr) IGatewayRateLimitDo
	Having(conds ...gen.Condition) IGatewayRateLimitDo
	Limit(limit int) IGatewayRateLimitDo
	Offset(offset int) IGatewayRateLimitDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGatewayRateLimitDo
	Unscoped() IGatewayRateLimitDo
	Create(values ...*model.GatewayRateLimit) error
	CreateInBatches(values []*model.GatewayRateLimit, batchSize int) error
	Save(values ...*model.GatewayRateLimit) error
	First() (*model.GatewayRateLimit, error)
	Take() (*model.GatewayRateLimit, error)
	Last() (*model.GatewayRateLimit, error)
	Find() ([]*model.GatewayRateLimit, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GatewayRateLimit, err error)
	FindInBatches(result *[]*model.GatewayRateLimit, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.GatewayRateLimit) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGatewayRateLimitDo
	Assign(attrs ...field.AssignExpr) IGatewayRateLimitDo
	Joins(fields ...field.RelationField) IGatewayRateLimitDo
	Preload(fields ...field.RelationField) IGatewayRateLimitDo
	FirstOrInit() (*model.GatewayRateLimit, error)
	FirstOrCreate() (*model.GatewayRateLimit, error)
	FindByPage(offset int, limit int) (result []*model.GatewayRateLimit, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGatewayRateLimitDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g gatewayRateLimitDo) Debug() IGatewayRateLimitDo {
	return g.withDO(g.DO.Debug())
}

func (g gatewayRateLimitDo) WithContext(ctx context.Context) IGatewayRateLimitDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g gatewayRateLimitDo) ReadDB() IGatewayRateLimitDo {
	return g.Clauses(dbresolver.Read)
}

func (g gatewayRateLimitDo) WriteDB() IGatewayRateLimitDo {
	return g.Clauses(dbresolver.Write)
}

func (g gatewayRateLimitDo) Session(config *gorm.Session) IGatewayRateLimitDo {
	return g.withDO(g.DO.Session(config))
}

func (g gatewayRateLimitDo) Clauses(conds ...clause.Expression) IGatewayRateLimitDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g gatewayRateLimitDo) Returning(value interface{}, columns ...string) IGatewayRateLimitDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g gatewayRateLimitDo) Not(conds ...gen.Condition) IGatewayRateLimitDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g gatewayRateLimitDo) Or(conds ...gen.Condition) IGatewayRateLimitDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g gatewayRateLimitDo) Select(conds ...field.Expr) IGatewayRateLimitDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g gatewayRateLimitDo) Where(conds ...gen.Condition) IGatewayRateLimitDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g gatewayRateLimitDo) Order(conds ...field.Expr) IGatewayRateLimitDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g gatewayRateLimitDo) Distinct(cols ...field.Expr) IGatewayRateLimitDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g gatewayRateLimitDo) Omit(cols ...field.Expr) IGatewayRateLimitDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g gatewayRateLimitDo) Join(table schema.Tabler, on ...field.Expr) IGatewayRateLimitDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g gatewayRateLimitDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGatewayRateLimitDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g gatewayRateLimitDo) RightJoin(table schema.Tabler, on ...field.Expr) IGatewayRateLimitDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g gatewayRateLimitDo) Group(cols ...field.Expr) IGatewayRateLimitDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g gatewayRateLimitDo) Having(conds ...gen.Condition) IGatewayRateLimitDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g gatewayRateLimitDo) Limit(limit int) IGatewayRateLimitDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g gatewayRateLimitDo) Offset(offset int) IGatewayRateLimitDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g gatewayRateLimitDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGatewayRateLimitDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g gatewayRateLimitDo) Unscoped() IGatewayRateLimitDo {
	return g.withDO(g.DO.Unscoped())
}

func (g gatewayRateLimitDo) Create(values ...*model.GatewayRateLimit) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g gatewayRateLimitDo) CreateInBatches(values []*model.GatewayRateLimit, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g gatewayRateLimitDo) Save(values ...*model.GatewayRateLimit) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g gatewayRateLimitDo) First() (*model.GatewayRateLimit, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GatewayRateLimit), nil
	}
}

func (g gatewayRateLimitDo) Take() (*model.GatewayRateLimit, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GatewayRateLimit), nil
	}
}

func (g gatewayRateLimitDo) Last() (*model.GatewayRateLimit, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GatewayRateLimit), nil
	}
}

func (g gatewayRateLimitDo) Find() ([]*model.GatewayRateLimit, error) {
	result, err := g.DO.Find()
	return result.([]*model.GatewayRateLimit), err
}

func (g gatewayRateLimitDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GatewayRateLimit, err error) {
	buf := make([]*model.GatewayRateLimit, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g gatewayRateLimitDo) FindInBatches(result *[]*model.GatewayRateLimit, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g gatewayRateLimitDo) Attrs(attrs ...field.AssignExpr) IGatewayRateLimitDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g gatewayRateLimitDo) Assign(attrs ...field.AssignExpr) IGatewayRateLimitDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g gatewayRateLimitDo) Joins(fields ...field.RelationField) IGatewayRateLimitDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g gatewayRateLimitDo) Preload(fields ...field.RelationField) IGatewayRateLimitDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g gatewayRateLimitDo) FirstOrInit() (*model.GatewayRateLimit, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GatewayRateLimit), nil
	}
}

func (g gatewayRateLimitDo) FirstOrCreate() (*model.GatewayRateLimit, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GatewayRateLimit), nil
	}
}

func (g gatewayRateLimitDo) FindByPage(offset int, limit int) (result []*model.GatewayRateLimit, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g gatewayRateLimitDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g gatewayRateLimitDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g gatewayRateLimitDo) Delete(models ...*model.GatewayRateLimit) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *gatewayRateLimitDo) withDO(do gen.Dao) *gatewayRateLimitDo {
	g.DO = *do.(*gen.DO)
	return g
}
