// Code generated by hertz generator.

package friend

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _friendMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfriendlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _additionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addfriendMw() []app.HandlerFunc {
	// your code...
	return nil
}
