// Code generated by hertz generator.

package chat

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chatMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _textMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _refreshtextMw() []app.HandlerFunc {
	// your code...
	return nil
}
