// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package infra

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *NodeConfig) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_NodeConfig[number], err)
}

func (x *NodeConfig) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.NodeId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *NodeConfig) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.NodeType, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *NodeConfig) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.Name, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *NodeConfig) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	if x.Params == nil {
		x.Params = make(map[string]string)
	}
	var key string
	var value string
	offset, err = fastpb.ReadMapEntry(buf, _type,
		func(buf []byte, _type int8) (offset int, err error) {
			key, offset, err = fastpb.ReadString(buf, _type)
			return offset, err
		},
		func(buf []byte, _type int8) (offset int, err error) {
			value, offset, err = fastpb.ReadString(buf, _type)
			return offset, err
		})
	if err != nil {
		return offset, err
	}
	x.Params[key] = value
	return offset, nil
}

func (x *NodeConfig) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	var v string
	v, offset, err = fastpb.ReadString(buf, _type)
	if err != nil {
		return offset, err
	}
	x.InputNodes = append(x.InputNodes, v)
	return offset, err
}

func (x *TriggerConfig) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_TriggerConfig[number], err)
}

func (x *TriggerConfig) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v int32
	v, offset, err = fastpb.ReadInt32(buf, _type)
	if err != nil {
		return offset, err
	}
	x.Type = TriggerType(v)
	return offset, nil
}

func (x *TriggerConfig) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.CronExpr, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *TriggerConfig) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.WebhookUrl, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *TriggerConfig) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.WebhookAuth, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *TriggerConfig) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	x.WebhookSecret, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ErrorInfo) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ErrorInfo[number], err)
}

func (x *ErrorInfo) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v int32
	v, offset, err = fastpb.ReadInt32(buf, _type)
	if err != nil {
		return offset, err
	}
	x.ErrorType = ErrorType(v)
	return offset, nil
}

func (x *ErrorInfo) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.ErrorMsg, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ErrorInfo) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.ErrorStack, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ErrorInfo) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.NodeId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ErrorInfo) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	x.ErrorTime, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *NodeConfig) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	return offset
}

func (x *NodeConfig) fastWriteField1(buf []byte) (offset int) {
	if x.NodeId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetNodeId())
	return offset
}

func (x *NodeConfig) fastWriteField2(buf []byte) (offset int) {
	if x.NodeType == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetNodeType())
	return offset
}

func (x *NodeConfig) fastWriteField3(buf []byte) (offset int) {
	if x.Name == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetName())
	return offset
}

func (x *NodeConfig) fastWriteField4(buf []byte) (offset int) {
	if x.Params == nil {
		return offset
	}
	for k, v := range x.GetParams() {
		offset += fastpb.WriteMapEntry(buf[offset:], 4,
			func(buf []byte, numTagOrKey, numIdxOrVal int32) int {
				offset := 0
				offset += fastpb.WriteString(buf[offset:], numTagOrKey, k)
				offset += fastpb.WriteString(buf[offset:], numIdxOrVal, v)
				return offset
			})
	}
	return offset
}

func (x *NodeConfig) fastWriteField5(buf []byte) (offset int) {
	if len(x.InputNodes) == 0 {
		return offset
	}
	for i := range x.GetInputNodes() {
		offset += fastpb.WriteString(buf[offset:], 5, x.GetInputNodes()[i])
	}
	return offset
}

func (x *TriggerConfig) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	return offset
}

func (x *TriggerConfig) fastWriteField1(buf []byte) (offset int) {
	if x.Type == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 1, int32(x.GetType()))
	return offset
}

func (x *TriggerConfig) fastWriteField2(buf []byte) (offset int) {
	if x.CronExpr == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetCronExpr())
	return offset
}

func (x *TriggerConfig) fastWriteField3(buf []byte) (offset int) {
	if x.WebhookUrl == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetWebhookUrl())
	return offset
}

func (x *TriggerConfig) fastWriteField4(buf []byte) (offset int) {
	if !x.WebhookAuth {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 4, x.GetWebhookAuth())
	return offset
}

func (x *TriggerConfig) fastWriteField5(buf []byte) (offset int) {
	if x.WebhookSecret == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 5, x.GetWebhookSecret())
	return offset
}

func (x *ErrorInfo) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	return offset
}

func (x *ErrorInfo) fastWriteField1(buf []byte) (offset int) {
	if x.ErrorType == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 1, int32(x.GetErrorType()))
	return offset
}

func (x *ErrorInfo) fastWriteField2(buf []byte) (offset int) {
	if x.ErrorMsg == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetErrorMsg())
	return offset
}

func (x *ErrorInfo) fastWriteField3(buf []byte) (offset int) {
	if x.ErrorStack == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetErrorStack())
	return offset
}

func (x *ErrorInfo) fastWriteField4(buf []byte) (offset int) {
	if x.NodeId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetNodeId())
	return offset
}

func (x *ErrorInfo) fastWriteField5(buf []byte) (offset int) {
	if x.ErrorTime == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 5, x.GetErrorTime())
	return offset
}

func (x *NodeConfig) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	return n
}

func (x *NodeConfig) sizeField1() (n int) {
	if x.NodeId == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetNodeId())
	return n
}

func (x *NodeConfig) sizeField2() (n int) {
	if x.NodeType == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetNodeType())
	return n
}

func (x *NodeConfig) sizeField3() (n int) {
	if x.Name == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetName())
	return n
}

func (x *NodeConfig) sizeField4() (n int) {
	if x.Params == nil {
		return n
	}
	for k, v := range x.GetParams() {
		n += fastpb.SizeMapEntry(4,
			func(numTagOrKey, numIdxOrVal int32) int {
				n := 0
				n += fastpb.SizeString(numTagOrKey, k)
				n += fastpb.SizeString(numIdxOrVal, v)
				return n
			})
	}
	return n
}

func (x *NodeConfig) sizeField5() (n int) {
	if len(x.InputNodes) == 0 {
		return n
	}
	for i := range x.GetInputNodes() {
		n += fastpb.SizeString(5, x.GetInputNodes()[i])
	}
	return n
}

func (x *TriggerConfig) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	return n
}

func (x *TriggerConfig) sizeField1() (n int) {
	if x.Type == 0 {
		return n
	}
	n += fastpb.SizeInt32(1, int32(x.GetType()))
	return n
}

func (x *TriggerConfig) sizeField2() (n int) {
	if x.CronExpr == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetCronExpr())
	return n
}

func (x *TriggerConfig) sizeField3() (n int) {
	if x.WebhookUrl == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetWebhookUrl())
	return n
}

func (x *TriggerConfig) sizeField4() (n int) {
	if !x.WebhookAuth {
		return n
	}
	n += fastpb.SizeBool(4, x.GetWebhookAuth())
	return n
}

func (x *TriggerConfig) sizeField5() (n int) {
	if x.WebhookSecret == "" {
		return n
	}
	n += fastpb.SizeString(5, x.GetWebhookSecret())
	return n
}

func (x *ErrorInfo) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	return n
}

func (x *ErrorInfo) sizeField1() (n int) {
	if x.ErrorType == 0 {
		return n
	}
	n += fastpb.SizeInt32(1, int32(x.GetErrorType()))
	return n
}

func (x *ErrorInfo) sizeField2() (n int) {
	if x.ErrorMsg == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetErrorMsg())
	return n
}

func (x *ErrorInfo) sizeField3() (n int) {
	if x.ErrorStack == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetErrorStack())
	return n
}

func (x *ErrorInfo) sizeField4() (n int) {
	if x.NodeId == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetNodeId())
	return n
}

func (x *ErrorInfo) sizeField5() (n int) {
	if x.ErrorTime == 0 {
		return n
	}
	n += fastpb.SizeInt64(5, x.GetErrorTime())
	return n
}

var fieldIDToName_NodeConfig = map[int32]string{
	1: "NodeId",
	2: "NodeType",
	3: "Name",
	4: "Params",
	5: "InputNodes",
}

var fieldIDToName_TriggerConfig = map[int32]string{
	1: "Type",
	2: "CronExpr",
	3: "WebhookUrl",
	4: "WebhookAuth",
	5: "WebhookSecret",
}

var fieldIDToName_ErrorInfo = map[int32]string{
	1: "ErrorType",
	2: "ErrorMsg",
	3: "ErrorStack",
	4: "NodeId",
	5: "ErrorTime",
}
