// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package exeution_manager

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
	api "github.com/fuhanyang/CYGlowFlow/rpc_gen/kitex_gen/api"
	common "github.com/fuhanyang/CYGlowFlow/rpc_gen/kitex_gen/common"
	infra "github.com/fuhanyang/CYGlowFlow/rpc_gen/kitex_gen/workflow/infra/infra"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *ExecuteWorkflowRequest) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ExecuteWorkflowRequest[number], err)
}

func (x *ExecuteWorkflowRequest) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.WorkflowId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ExecuteWorkflowRequest) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	if x.InputData == nil {
		x.InputData = make(map[string]string)
	}
	var key string
	var value string
	offset, err = fastpb.ReadMapEntry(buf, _type,
		func(buf []byte, _type int8) (offset int, err error) {
			key, offset, err = fastpb.ReadString(buf, _type)
			return offset, err
		},
		func(buf []byte, _type int8) (offset int, err error) {
			value, offset, err = fastpb.ReadString(buf, _type)
			return offset, err
		})
	if err != nil {
		return offset, err
	}
	x.InputData[key] = value
	return offset, nil
}

func (x *ExecuteWorkflowRequest) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.WaitForResult, offset, err = fastpb.ReadBool(buf, _type)
	return offset, err
}

func (x *ExecutionInfo) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 6:
		offset, err = x.fastReadField6(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 7:
		offset, err = x.fastReadField7(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 8:
		offset, err = x.fastReadField8(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 9:
		offset, err = x.fastReadField9(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 10:
		offset, err = x.fastReadField10(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ExecutionInfo[number], err)
}

func (x *ExecutionInfo) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.ExecutionId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ExecutionInfo) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.WorkflowId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ExecutionInfo) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	var v int32
	v, offset, err = fastpb.ReadInt32(buf, _type)
	if err != nil {
		return offset, err
	}
	x.Status = infra.ExecutionStatus(v)
	return offset, nil
}

func (x *ExecutionInfo) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.StartTime, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ExecutionInfo) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	x.EndTime, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ExecutionInfo) fastReadField6(buf []byte, _type int8) (offset int, err error) {
	x.Duration, offset, err = fastpb.ReadDouble(buf, _type)
	return offset, err
}

func (x *ExecutionInfo) fastReadField7(buf []byte, _type int8) (offset int, err error) {
	if x.InputData == nil {
		x.InputData = make(map[string]string)
	}
	var key string
	var value string
	offset, err = fastpb.ReadMapEntry(buf, _type,
		func(buf []byte, _type int8) (offset int, err error) {
			key, offset, err = fastpb.ReadString(buf, _type)
			return offset, err
		},
		func(buf []byte, _type int8) (offset int, err error) {
			value, offset, err = fastpb.ReadString(buf, _type)
			return offset, err
		})
	if err != nil {
		return offset, err
	}
	x.InputData[key] = value
	return offset, nil
}

func (x *ExecutionInfo) fastReadField8(buf []byte, _type int8) (offset int, err error) {
	if x.OutputData == nil {
		x.OutputData = make(map[string]string)
	}
	var key string
	var value string
	offset, err = fastpb.ReadMapEntry(buf, _type,
		func(buf []byte, _type int8) (offset int, err error) {
			key, offset, err = fastpb.ReadString(buf, _type)
			return offset, err
		},
		func(buf []byte, _type int8) (offset int, err error) {
			value, offset, err = fastpb.ReadString(buf, _type)
			return offset, err
		})
	if err != nil {
		return offset, err
	}
	x.OutputData[key] = value
	return offset, nil
}

func (x *ExecutionInfo) fastReadField9(buf []byte, _type int8) (offset int, err error) {
	var v infra.ErrorInfo
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.Error = &v
	return offset, nil
}

func (x *ExecutionInfo) fastReadField10(buf []byte, _type int8) (offset int, err error) {
	x.Executor, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ExecutionQueryRequest) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 5:
		offset, err = x.fastReadField5(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ExecutionQueryRequest[number], err)
}

func (x *ExecutionQueryRequest) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v common.PageRequest
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.Page = &v
	return offset, nil
}

func (x *ExecutionQueryRequest) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.WorkflowId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ExecutionQueryRequest) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	var v int32
	v, offset, err = fastpb.ReadInt32(buf, _type)
	if err != nil {
		return offset, err
	}
	x.Status = infra.ExecutionStatus(v)
	return offset, nil
}

func (x *ExecutionQueryRequest) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.StartTime, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *ExecutionQueryRequest) fastReadField5(buf []byte, _type int8) (offset int, err error) {
	x.EndTime, offset, err = fastpb.ReadInt64(buf, _type)
	return offset, err
}

func (x *GetExecutionDetailRequest) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_GetExecutionDetailRequest[number], err)
}

func (x *GetExecutionDetailRequest) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.ExecutionId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *CancelExecutionRequest) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_CancelExecutionRequest[number], err)
}

func (x *CancelExecutionRequest) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.ExecutionId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ExecuteWorkflowRequest) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *ExecuteWorkflowRequest) fastWriteField1(buf []byte) (offset int) {
	if x.WorkflowId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetWorkflowId())
	return offset
}

func (x *ExecuteWorkflowRequest) fastWriteField2(buf []byte) (offset int) {
	if x.InputData == nil {
		return offset
	}
	for k, v := range x.GetInputData() {
		offset += fastpb.WriteMapEntry(buf[offset:], 2,
			func(buf []byte, numTagOrKey, numIdxOrVal int32) int {
				offset := 0
				offset += fastpb.WriteString(buf[offset:], numTagOrKey, k)
				offset += fastpb.WriteString(buf[offset:], numIdxOrVal, v)
				return offset
			})
	}
	return offset
}

func (x *ExecuteWorkflowRequest) fastWriteField3(buf []byte) (offset int) {
	if !x.WaitForResult {
		return offset
	}
	offset += fastpb.WriteBool(buf[offset:], 3, x.GetWaitForResult())
	return offset
}

func (x *ExecutionInfo) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	offset += x.fastWriteField6(buf[offset:])
	offset += x.fastWriteField7(buf[offset:])
	offset += x.fastWriteField8(buf[offset:])
	offset += x.fastWriteField9(buf[offset:])
	offset += x.fastWriteField10(buf[offset:])
	return offset
}

func (x *ExecutionInfo) fastWriteField1(buf []byte) (offset int) {
	if x.ExecutionId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetExecutionId())
	return offset
}

func (x *ExecutionInfo) fastWriteField2(buf []byte) (offset int) {
	if x.WorkflowId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetWorkflowId())
	return offset
}

func (x *ExecutionInfo) fastWriteField3(buf []byte) (offset int) {
	if x.Status == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 3, int32(x.GetStatus()))
	return offset
}

func (x *ExecutionInfo) fastWriteField4(buf []byte) (offset int) {
	if x.StartTime == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 4, x.GetStartTime())
	return offset
}

func (x *ExecutionInfo) fastWriteField5(buf []byte) (offset int) {
	if x.EndTime == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 5, x.GetEndTime())
	return offset
}

func (x *ExecutionInfo) fastWriteField6(buf []byte) (offset int) {
	if x.Duration == 0 {
		return offset
	}
	offset += fastpb.WriteDouble(buf[offset:], 6, x.GetDuration())
	return offset
}

func (x *ExecutionInfo) fastWriteField7(buf []byte) (offset int) {
	if x.InputData == nil {
		return offset
	}
	for k, v := range x.GetInputData() {
		offset += fastpb.WriteMapEntry(buf[offset:], 7,
			func(buf []byte, numTagOrKey, numIdxOrVal int32) int {
				offset := 0
				offset += fastpb.WriteString(buf[offset:], numTagOrKey, k)
				offset += fastpb.WriteString(buf[offset:], numIdxOrVal, v)
				return offset
			})
	}
	return offset
}

func (x *ExecutionInfo) fastWriteField8(buf []byte) (offset int) {
	if x.OutputData == nil {
		return offset
	}
	for k, v := range x.GetOutputData() {
		offset += fastpb.WriteMapEntry(buf[offset:], 8,
			func(buf []byte, numTagOrKey, numIdxOrVal int32) int {
				offset := 0
				offset += fastpb.WriteString(buf[offset:], numTagOrKey, k)
				offset += fastpb.WriteString(buf[offset:], numIdxOrVal, v)
				return offset
			})
	}
	return offset
}

func (x *ExecutionInfo) fastWriteField9(buf []byte) (offset int) {
	if x.Error == nil {
		return offset
	}
	offset += fastpb.WriteMessage(buf[offset:], 9, x.GetError())
	return offset
}

func (x *ExecutionInfo) fastWriteField10(buf []byte) (offset int) {
	if x.Executor == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 10, x.GetExecutor())
	return offset
}

func (x *ExecutionQueryRequest) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	offset += x.fastWriteField5(buf[offset:])
	return offset
}

func (x *ExecutionQueryRequest) fastWriteField1(buf []byte) (offset int) {
	if x.Page == nil {
		return offset
	}
	offset += fastpb.WriteMessage(buf[offset:], 1, x.GetPage())
	return offset
}

func (x *ExecutionQueryRequest) fastWriteField2(buf []byte) (offset int) {
	if x.WorkflowId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetWorkflowId())
	return offset
}

func (x *ExecutionQueryRequest) fastWriteField3(buf []byte) (offset int) {
	if x.Status == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 3, int32(x.GetStatus()))
	return offset
}

func (x *ExecutionQueryRequest) fastWriteField4(buf []byte) (offset int) {
	if x.StartTime == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 4, x.GetStartTime())
	return offset
}

func (x *ExecutionQueryRequest) fastWriteField5(buf []byte) (offset int) {
	if x.EndTime == 0 {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 5, x.GetEndTime())
	return offset
}

func (x *GetExecutionDetailRequest) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *GetExecutionDetailRequest) fastWriteField1(buf []byte) (offset int) {
	if x.ExecutionId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetExecutionId())
	return offset
}

func (x *CancelExecutionRequest) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *CancelExecutionRequest) fastWriteField1(buf []byte) (offset int) {
	if x.ExecutionId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetExecutionId())
	return offset
}

func (x *ExecuteWorkflowRequest) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *ExecuteWorkflowRequest) sizeField1() (n int) {
	if x.WorkflowId == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetWorkflowId())
	return n
}

func (x *ExecuteWorkflowRequest) sizeField2() (n int) {
	if x.InputData == nil {
		return n
	}
	for k, v := range x.GetInputData() {
		n += fastpb.SizeMapEntry(2,
			func(numTagOrKey, numIdxOrVal int32) int {
				n := 0
				n += fastpb.SizeString(numTagOrKey, k)
				n += fastpb.SizeString(numIdxOrVal, v)
				return n
			})
	}
	return n
}

func (x *ExecuteWorkflowRequest) sizeField3() (n int) {
	if !x.WaitForResult {
		return n
	}
	n += fastpb.SizeBool(3, x.GetWaitForResult())
	return n
}

func (x *ExecutionInfo) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	n += x.sizeField6()
	n += x.sizeField7()
	n += x.sizeField8()
	n += x.sizeField9()
	n += x.sizeField10()
	return n
}

func (x *ExecutionInfo) sizeField1() (n int) {
	if x.ExecutionId == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetExecutionId())
	return n
}

func (x *ExecutionInfo) sizeField2() (n int) {
	if x.WorkflowId == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetWorkflowId())
	return n
}

func (x *ExecutionInfo) sizeField3() (n int) {
	if x.Status == 0 {
		return n
	}
	n += fastpb.SizeInt32(3, int32(x.GetStatus()))
	return n
}

func (x *ExecutionInfo) sizeField4() (n int) {
	if x.StartTime == 0 {
		return n
	}
	n += fastpb.SizeInt64(4, x.GetStartTime())
	return n
}

func (x *ExecutionInfo) sizeField5() (n int) {
	if x.EndTime == 0 {
		return n
	}
	n += fastpb.SizeInt64(5, x.GetEndTime())
	return n
}

func (x *ExecutionInfo) sizeField6() (n int) {
	if x.Duration == 0 {
		return n
	}
	n += fastpb.SizeDouble(6, x.GetDuration())
	return n
}

func (x *ExecutionInfo) sizeField7() (n int) {
	if x.InputData == nil {
		return n
	}
	for k, v := range x.GetInputData() {
		n += fastpb.SizeMapEntry(7,
			func(numTagOrKey, numIdxOrVal int32) int {
				n := 0
				n += fastpb.SizeString(numTagOrKey, k)
				n += fastpb.SizeString(numIdxOrVal, v)
				return n
			})
	}
	return n
}

func (x *ExecutionInfo) sizeField8() (n int) {
	if x.OutputData == nil {
		return n
	}
	for k, v := range x.GetOutputData() {
		n += fastpb.SizeMapEntry(8,
			func(numTagOrKey, numIdxOrVal int32) int {
				n := 0
				n += fastpb.SizeString(numTagOrKey, k)
				n += fastpb.SizeString(numIdxOrVal, v)
				return n
			})
	}
	return n
}

func (x *ExecutionInfo) sizeField9() (n int) {
	if x.Error == nil {
		return n
	}
	n += fastpb.SizeMessage(9, x.GetError())
	return n
}

func (x *ExecutionInfo) sizeField10() (n int) {
	if x.Executor == "" {
		return n
	}
	n += fastpb.SizeString(10, x.GetExecutor())
	return n
}

func (x *ExecutionQueryRequest) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	n += x.sizeField5()
	return n
}

func (x *ExecutionQueryRequest) sizeField1() (n int) {
	if x.Page == nil {
		return n
	}
	n += fastpb.SizeMessage(1, x.GetPage())
	return n
}

func (x *ExecutionQueryRequest) sizeField2() (n int) {
	if x.WorkflowId == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetWorkflowId())
	return n
}

func (x *ExecutionQueryRequest) sizeField3() (n int) {
	if x.Status == 0 {
		return n
	}
	n += fastpb.SizeInt32(3, int32(x.GetStatus()))
	return n
}

func (x *ExecutionQueryRequest) sizeField4() (n int) {
	if x.StartTime == 0 {
		return n
	}
	n += fastpb.SizeInt64(4, x.GetStartTime())
	return n
}

func (x *ExecutionQueryRequest) sizeField5() (n int) {
	if x.EndTime == 0 {
		return n
	}
	n += fastpb.SizeInt64(5, x.GetEndTime())
	return n
}

func (x *GetExecutionDetailRequest) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *GetExecutionDetailRequest) sizeField1() (n int) {
	if x.ExecutionId == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetExecutionId())
	return n
}

func (x *CancelExecutionRequest) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *CancelExecutionRequest) sizeField1() (n int) {
	if x.ExecutionId == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetExecutionId())
	return n
}

var fieldIDToName_ExecuteWorkflowRequest = map[int32]string{
	1: "WorkflowId",
	2: "InputData",
	3: "WaitForResult",
}

var fieldIDToName_ExecutionInfo = map[int32]string{
	1:  "ExecutionId",
	2:  "WorkflowId",
	3:  "Status",
	4:  "StartTime",
	5:  "EndTime",
	6:  "Duration",
	7:  "InputData",
	8:  "OutputData",
	9:  "Error",
	10: "Executor",
}

var fieldIDToName_ExecutionQueryRequest = map[int32]string{
	1: "Page",
	2: "WorkflowId",
	3: "Status",
	4: "StartTime",
	5: "EndTime",
}

var fieldIDToName_GetExecutionDetailRequest = map[int32]string{
	1: "ExecutionId",
}

var fieldIDToName_CancelExecutionRequest = map[int32]string{
	1: "ExecutionId",
}

var _ = common.File_common_proto
var _ = infra.File_workflow_infra_infra_proto
var _ = api.File_api_proto
