// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGatewayRateLimit = "gateway_rate_limits"

// GatewayRateLimit 限流规则表
type GatewayRateLimit struct {
	ID          uint64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	RoutePath   string     `gorm:"column:route_path;type:varchar(128);not null;uniqueIndex:idx_route,priority:1;comment:限流的路由路径/规则" json:"route_path"`                 // 限流的路由路径/规则
	LimitMethod *string    `gorm:"column:limit_method;type:varchar(10);uniqueIndex:idx_route,priority:2;default:ALL;comment:限流方法(ALL, GET, POST)" json:"limit_method"` // 限流方法(ALL, GET, POST)
	Capacity    *int32     `gorm:"column:capacity;type:int;not null;default:100;comment:令牌桶容量/最大并发数" json:"capacity"`                                                  // 令牌桶容量/最大并发数
	IntervalSec *int32     `gorm:"column:interval_sec;type:int;not null;default:1;comment:时间窗口(秒)" json:"interval_sec"`                                                // 时间窗口(秒)
	Enable      *int32     `gorm:"column:enable;type:tinyint;not null;default:1;comment:是否开启" json:"enable"`                                                           // 是否开启
	CreatedAt   *time.Time `gorm:"column:created_at;type:datetime;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:datetime;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName GatewayRateLimit's table name
func (*GatewayRateLimit) TableName() string {
	return TableNameGatewayRateLimit
}
