// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGatewayAccessLog = "gateway_access_logs"

// GatewayAccessLog 网关访问日志表
type GatewayAccessLog struct {
	ID         uint64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	TraceID    *string    `gorm:"column:trace_id;type:varchar(64);index:idx_trace_id,priority:1;comment:链路追踪ID" json:"trace_id"`                            // 链路追踪ID
	UserID     *uint64    `gorm:"column:user_id;type:bigint unsigned;index:idx_user_id,priority:1;comment:用户ID(未登录为0)" json:"user_id"`                      // 用户ID(未登录为0)
	IP         *string    `gorm:"column:ip;type:varchar(64);comment:访问IP" json:"ip"`                                                                        // 访问IP
	Method     *string    `gorm:"column:method;type:varchar(10);comment:请求方法" json:"method"`                                                                // 请求方法
	Path       *string    `gorm:"column:path;type:varchar(255);comment:请求路径" json:"path"`                                                                   // 请求路径
	Query      *string    `gorm:"column:query;type:text;comment:查询参数" json:"query"`                                                                         // 查询参数
	Body       *string    `gorm:"column:body;type:text;comment:请求体(可选截取)" json:"body"`                                                                      // 请求体(可选截取)
	StatusCode *int32     `gorm:"column:status_code;type:int;default:200;comment:HTTP状态码" json:"status_code"`                                               // HTTP状态码
	Latency    *int64     `gorm:"column:latency;type:bigint;comment:耗时(毫秒)" json:"latency"`                                                                 // 耗时(毫秒)
	ErrorMsg   *string    `gorm:"column:error_msg;type:varchar(255);comment:错误信息" json:"error_msg"`                                                         // 错误信息
	CreatedAt  *time.Time `gorm:"column:created_at;type:datetime;index:idx_created_at,priority:1;default:CURRENT_TIMESTAMP;comment:请求时间" json:"created_at"` // 请求时间
}

// TableName GatewayAccessLog's table name
func (*GatewayAccessLog) TableName() string {
	return TableNameGatewayAccessLog
}
