// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysUser = "sys_users"

// SysUser 系统用户表
type SysUser struct {
	ID        uint64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                       // 主键ID
	Username  string         `gorm:"column:username;type:varchar(64);not null;uniqueIndex:idx_username,priority:1;comment:用户名" json:"username"` // 用户名
	Password  string         `gorm:"column:password;type:varchar(128);not null;comment:加密后的密码" json:"password"`                                 // 加密后的密码
	Email     *string        `gorm:"column:email;type:varchar(128);index:idx_email,priority:1;comment:邮箱" json:"email"`                         // 邮箱
	Phone     *string        `gorm:"column:phone;type:varchar(20);comment:手机号" json:"phone"`                                                    // 手机号
	Avatar    *string        `gorm:"column:avatar;type:varchar(255);comment:头像URL" json:"avatar"`                                               // 头像URL
	Status    *int32         `gorm:"column:status;type:tinyint;not null;default:1;comment:状态 1:正常 2:冻结" json:"status"`                          // 状态 1:正常 2:冻结
	CreatedAt *time.Time     `gorm:"column:created_at;type:datetime;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                  // 创建时间
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                  // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间(软删除)" json:"deleted_at"`                                       // 删除时间(软删除)
}

// TableName SysUser's table name
func (*SysUser) TableName() string {
	return TableNameSysUser
}
