// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysRole = "sys_roles"

// SysRole 角色表
type SysRole struct {
	ID          uint64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	RoleName    string         `gorm:"column:role_name;type:varchar(64);not null;comment:角色名称" json:"role_name"`                                            // 角色名称
	RoleKey     string         `gorm:"column:role_key;type:varchar(64);not null;uniqueIndex:idx_role_key,priority:1;comment:角色标识(如 admin)" json:"role_key"` // 角色标识(如 admin)
	Description *string        `gorm:"column:description;type:varchar(255);comment:描述" json:"description"`                                                  // 描述
	Status      *int32         `gorm:"column:status;type:tinyint;not null;default:1;comment:状态 1:正常 0:禁用" json:"status"`                                    // 状态 1:正常 0:禁用
	CreatedAt   *time.Time     `gorm:"column:created_at;type:datetime;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   *time.Time     `gorm:"column:updated_at;type:datetime;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:datetime" json:"deleted_at"`
}

// TableName SysRole's table name
func (*SysRole) TableName() string {
	return TableNameSysRole
}
