// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysPermission = "sys_permissions"

// SysPermission 权限表
type SysPermission struct {
	ID        uint64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	ParentID  *uint64        `gorm:"column:parent_id;type:bigint unsigned;index:idx_parent_id,priority:1;comment:父权限ID" json:"parent_id"` // 父权限ID
	Name      string         `gorm:"column:name;type:varchar(64);not null;comment:权限名称" json:"name"`                                      // 权限名称
	PermKey   string         `gorm:"column:perm_key;type:varchar(64);not null;comment:权限标识(如 user:list)" json:"perm_key"`                 // 权限标识(如 user:list)
	Type      *int32         `gorm:"column:type;type:tinyint;not null;default:1;comment:类型 1:菜单 2:按钮/API" json:"type"`                    // 类型 1:菜单 2:按钮/API
	Path      *string        `gorm:"column:path;type:varchar(128);comment:前端路由或后端API路径" json:"path"`                                      // 前端路由或后端API路径
	Method    *string        `gorm:"column:method;type:varchar(10);comment:HTTP方法(GET, POST等)" json:"method"`                             // HTTP方法(GET, POST等)
	CreatedAt *time.Time     `gorm:"column:created_at;type:datetime;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime" json:"deleted_at"`
}

// TableName SysPermission's table name
func (*SysPermission) TableName() string {
	return TableNameSysPermission
}
