// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "user"

// User 用户表
type User struct {
	ID         uint64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:用户ID" json:"id"`                             // 用户ID
	AccountNum int64          `gorm:"column:account_num;type:bigint;not null;uniqueIndex:uk_account_num,priority:1;comment:账号(数字)" json:"account_num"` // 账号(数字)
	Name       *string        `gorm:"column:name;type:varchar(64);comment:昵称" json:"name"`                                                             // 昵称
	Email      *string        `gorm:"column:email;type:varchar(128);uniqueIndex:uk_email,priority:1;comment:邮箱" json:"email"`                          // 邮箱
	Phone      *string        `gorm:"column:phone;type:varchar(20);uniqueIndex:uk_phone,priority:1;comment:手机号" json:"phone"`                          // 手机号
	AvatarURL  *string        `gorm:"column:avatar_url;type:varchar(255);comment:头像URL" json:"avatar_url"`                                             // 头像URL
	Desc       *string        `gorm:"column:desc;type:varchar(255);comment:个人简介" json:"desc"`                                                          // 个人简介
	Password   string         `gorm:"column:password;type:varchar(255);not null;comment:加密后的密码" json:"password"`                                       // 加密后的密码
	Status     *int32         `gorm:"column:status;type:int;not null;default:1;comment:状态 1:正常 2:冻结" json:"status"`                                    // 状态 1:正常 2:冻结
	CreatedAt  *time.Time     `gorm:"column:created_at;type:datetime;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                        // 创建时间
	UpdatedAt  *time.Time     `gorm:"column:updated_at;type:datetime;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                        // 更新时间
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;index:idx_deleted_at,priority:1;comment:删除时间" json:"deleted_at"`                  // 删除时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
